version: "3.8"
services:
  pg:
    image: postgres:14
    container_name: pgdb_monitors_local
    restart: always
    healthcheck:
      test: "pg_isready"
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: custom_dev_db
    volumes:
      - pg:/var/lib/pstgresql/data
    networks:
      - api
